#' Fetch USQ Data from AARNET Cloudstor, OneDrive or Sharepoint
#
#' @param url User provided url generated by "sharing" the file via any of the
#' supported services

fetch_data <- function(url) {

}
