#' Fetch Data from AARNET Cloudstor, OneDrive, Sharepoint, GDrive, GitHub or any Other Web-based Provider
#'
#' Given a URL that resolves to a downloadable data file, `fetch_data()` will
#' attempt to download and import the data.
#'
#' @param url User provided url generated by "sharing" the file via any of the
#' supported filetypes of [rio::import()], also works with raw GitHub or any
#' other provider from which a raw data file can be downloaded and imported.
#' Character.
#' @param which User provided spreadhseet for '.xslx', 'Google Sheets' and
#'  '.ods' files either as the number of the sheet in order or the name of the
#'  sheet. For .Rdata objects it can be an object name. See [rio::import()] for
#'  further details
#' @param file_ext Optional user provided file type extension. If provided,
#'  `fetch_data()` will attempt to use this as instruction about the file
#'  type being imported, _e.g._ "xlsx" or "csv". If not provided,
#'  `fetch_data()` will do its best to determine the file type automagically and
#'  import the file. Character.
#' @export fetch_data
#' @return A `data.frame`` of data derived from any '.csv', '.xls(x)', '.txt',
#' or '.ods' file provided that \R can import

fetch_data <- function(url,
                       which = NULL,
                       file_ext = NULL) {
  # if this is a Google Sheets object, import it
  if (grepl("docs.google.com/spreadsheets", url)) {
    f <- rio::import(file = url, which = which)
  }
  # if the URL says it's a .csv import it
  if  (substr(url, nchar(url) - 3, nchar(url)) == ".csv") {
    f <- rio::import(file = url)
  }
  # if the URL says it's a .txt file, import it
  if (substr(url, nchar(url) - 3, nchar(url)) == ".txt") {
    f <- rio::import(file = url, which = which)
  } else {
  # otherwise we'll download it and figure out what we have
  # create a file object in the tempdir() to store and read the download
  f <- file.path(tempdir(), "tmp")
  # download the file
  #
  # if the file is in OneDrive modify the URL to download the file
  if (grepl("https://usqprd-my.sharepoint.com", url)) {
    url <- gsub("\\?.*$", "\\?download=1", url)
  }

  curl::curl_download(url = url,
                      destfile = f,
                      mode = "wb")
  # did the user give us a file extension?
  if (!is.null(file_ext)) {
    # did the user include the "." before the file extension?
    if (substr(file_ext, 1, 1) != ".") {
      file_ext <- paste0(".", file_ext)
    }
    # create a full filename and extension
    f <- paste0(f, file_ext)
  } else {
    # determine the file type so that we can import the file
    ft <- dqmagic::file_type(f)

    # import the file
    if (ft == "Microsoft Excel 2007+") {
      file.rename(f, paste0(f, ".xlsx"))
      f <- paste0(f, ".xlsx")
    } else if (ft == "ASCII text") {
      file.rename(f, paste0(f, ".txt"))
      f <- paste0(f, ".txt")
    } else
      stop("Cannot determine the file type. Please provide a file extension.")
  }

  # finally import file
  if (!is.null(which)) {
    f <- rio::import(file = f, which = which)
  } else
    f <- rio::import(file = f)
}
return(as.data.frame(f))
}
